version: '2'
services:
  nginx:
   container_name: nginx-app
   image: nginx:stable
   restart: always
   ports:
   - 8983:8080
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  app:
    container_name: app
    image: solr:6.6-alpine
    ports:
      - 8982:8983
    depends_on:
      - nginx
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c